apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/pontusvision: "true"
    io.kompose.service: graphdb-nifi
  name: graphdb-nifi
spec:
  containers:
  - args:
    - /bin/bash
    - -c
    - |2 
      #echo Waiting for elasticsearch service start...;\n  #while ! nc -z elasticsearch
      #do\n    #sleep 1;\n  #done;\n  echo Connected!;\n
      LD_LIBRARY_PATH=:/tmp
      /orientdb/bin/server.sh
    env:
    - name: ORIENTDB_ROOT_PASSWORD
      valueFrom:
        #configMapKeyRef:
        secretKeyRef:
          name: pontus-graphdb
          key: ORIENTDB_ROOT_PASSWORD
    image: pontusvisiongdpr/pontus-track-graphdb-odb-pt:latest
    name: graphdb-nifi
    ports:
    - containerPort: 8183
    - containerPort: 7000
    - containerPort: 3001
    - containerPort: 2480
    - containerPort: 5007
    resources: {}
    volumeMounts:
    - mountPath: /run/secrets/mapping-salesforce-graph
      subPath: mapping-salesforce-graph
      name: mapping-salesforce-graph
  hostname: graphdb-nifi
  restartPolicy: OnFailure
  subdomain: pontus-demo-com
  volumes:
  - name: mapping-salesforce-graph
    secret:
      secretName: mapping-salesforce-graph
status: {}
