apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/pontusvision: "true"
    io.kompose.service: pontus-comply-keycloak
  name: pontus-comply-keycloak
spec:
  containers:
  - image: pontusvisiongdpr/pontus-comply-keycloak:latest
    name: pontus-comply-keycloak
    ports:
    - containerPort: 8080
    resources: {}
    securityContext:
      privileged: true
  hostname: pontus-comply-keycloak
  restartPolicy: OnFailure
  subdomain: pontus-demo-com
status: {}
