apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/pontusvision: "true"
    io.kompose.service: pontus-formio
  name: pontus-formio
spec:
  containers:
  - args:
    - /bin/bash
    - -c
    - |2

        echo Waiting for mongodb service start...;
        while ! nc -z pontus-formio-mongodb 27017;
        do
          sleep 1;
        done;
        sleep 10;
        echo Connected!;
        /opt/pontus/pontus-formio/current/bin/run-gui.sh
        #while [[ true ]]; do sleep 1; done
    image: pontusvisiongdpr/pontus-lgpd-formio:latest
    name: pontus-formio
    ports:
    - containerPort: 3005
    - containerPort: 8085
    resources: {}
    securityContext:
      privileged: true
  hostname: pontus-formio
  restartPolicy: OnFailure
  subdomain: pontus-demo-com
status: {}
