apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/pontusvision: "true"
    io.kompose.service: pontus-timescaledb
  name: pontus-timescaledb
spec:
  containers:
  - env:
    - name: PGUSER
      value: postgres
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pontus-timescaledb
          key: POSTGRES_PASSWORD
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: pontus-timescaledb
          key: POSTGRES_USER
    image: pontusvisiongdpr/timescaledb:latest
    name: pontus-timescaledb
    resources: {}
  hostname: pontus-timescaledb
  restartPolicy: OnFailure
  subdomain: pontus-demo-com
status: {}
