apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/pontusvision: "true"
    io.kompose.service: pontus-formio-mongodb
  name: pontus-formio-mongodb
spec:
  containers:
  - args:
    - /bin/bash
    - -c
    - "\n  docker-entrypoint.sh mongod &\n  if [[ ! -f /data/db/pv-init ]]; then\n
      \   sleep 5 \n    mongorestore /mongodb  \n    sleep 5 \n    touch /data/db/pv-init\n
      \ fi\n  wait %1\n"
    image: pontusvisiongdpr/pontus-lgpd-formio-mongodb:latest
    name: pontus-formio-mongodb
    ports:
    - containerPort: 27017
    resources: {}
  hostname: pontus-formio-mongodb
  restartPolicy: OnFailure
  subdomain: pontus-demo-com
status: {}
